### ISSUE TITLE
tbb::task_group in 5

### ISSUE THREAD

**Issue by jaki95** [HPCE/hpce-2018-cw2#82]
In **-5-**, I don't understand what is meant by "keep splitting the tasks down to the point of individual elements".  To my understanding, there are two recursive function calls which can be parallelised in two tasks as

```
group.run([&](){recurse(m,wn*wn,pIn,2*sIn,pOut,sOut);}); 
group.run([&](){recurse(m,wn*wn,pIn+sIn,2*sIn,pOut+sOut*m,sOut);});
```

How can this be further split into individual elements?

**Comment by DiederikVink** [comment]
Because this is a recursive call, every time you enter the recursive function you will split the task into 2 child processes in the **else** case (line 39-54) of the recuse function. This will keep running until the **n==1** or **n==2** case where each process has been reduced down to individual elements which is the furthest degree of splitting that can be achieved.
